# Generated by Django 5.0.6 on 2024-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono_area',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código de Área'),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono_numero',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='created_by',
            field=models.IntegerField(default=1, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='updated_by',
            field=models.IntegerField(default=1, verbose_name='Modificado por'),
        ),
    ]
